<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <ProjectReference Include="..\GuestFlow.Application\GuestFlow.Application.csproj" />
	  <ProjectReference Include="..\GuestFlow.Domain\GuestFlow.Domain.csproj" />
  </ItemGroup>

</Project>
