<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\GuestFlow.Domain\GuestFlow.Domain.csproj" />
    <ProjectReference Include="..\GuestFlow.Persistence\GuestFlow.Persistence.csproj" />
  </ItemGroup>

</Project>
