// <auto-generated />
using System;
using GuestFlow.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuestFlow.Persistence.Migrations
{
    [DbContext(typeof(GuestFlowDbContext))]
    [Migration("20250319060747_SeedGuestData")]
    partial class SeedGuestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.AirportEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Airports");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.CityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.CityTourEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationHours")
                        .HasColumnType("int");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TourDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("CityTours");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.DailyNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NoteDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonnelId");

                    b.ToTable("DailyNotes");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.DailyRevenueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DailyRevenues");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.GuestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.InvoicesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CityTourId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransferId")
                        .HasColumnType("int");

                    b.Property<int?>("YachtTourId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityTourId");

                    b.HasIndex("GuestId");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("TransferId");

                    b.HasIndex("YachtTourId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.PersonnelEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personnels");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.TransferEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DropoffAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFromAirport")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<string>("PickupAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransferDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirportId");

                    b.HasIndex("GuestId");

                    b.HasIndex("PersonnelId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.VehicleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DailyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.YachtTourEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfPeople")
                        .HasColumnType("int");

                    b.Property<int>("PersonnelId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SpecialRequest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TourDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GuestId");

                    b.HasIndex("PersonnelId");

                    b.ToTable("YachtTours");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Operations.GuestCityTour", b =>
                {
                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("CityTourId")
                        .HasColumnType("int");

                    b.HasKey("GuestId", "CityTourId");

                    b.HasIndex("CityTourId");

                    b.ToTable("GuestCityTours");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Operations.GuestYachtTour", b =>
                {
                    b.Property<int>("GuestId")
                        .HasColumnType("int");

                    b.Property<int>("YachtTourId")
                        .HasColumnType("int");

                    b.HasKey("GuestId", "YachtTourId");

                    b.HasIndex("YachtTourId");

                    b.ToTable("GuestYachtTours");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.AirportEntity", b =>
                {
                    b.HasOne("GuestFlow.Domain.Entities.Core.CityEntity", "City")
                        .WithMany("Airports")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.CityTourEntity", b =>
                {
                    b.HasOne("GuestFlow.Domain.Entities.Core.GuestEntity", "Guest")
                        .WithMany()
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestFlow.Domain.Entities.Core.PersonnelEntity", "Personnel")
                        .WithMany("CityTours")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.DailyNote", b =>
                {
                    b.HasOne("GuestFlow.Domain.Entities.Core.PersonnelEntity", "Personnel")
                        .WithMany("DailyNotes")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.InvoicesEntity", b =>
                {
                    b.HasOne("GuestFlow.Domain.Entities.Core.CityTourEntity", "CityTour")
                        .WithMany()
                        .HasForeignKey("CityTourId");

                    b.HasOne("GuestFlow.Domain.Entities.Core.GuestEntity", "Guest")
                        .WithMany("Invoices")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestFlow.Domain.Entities.Core.PersonnelEntity", "Personnel")
                        .WithMany("Invoices")
                        .HasForeignKey("PersonnelId");

                    b.HasOne("GuestFlow.Domain.Entities.Core.TransferEntity", "Transfer")
                        .WithMany("Invoices")
                        .HasForeignKey("TransferId");

                    b.HasOne("GuestFlow.Domain.Entities.Core.YachtTourEntity", "YachtTour")
                        .WithMany()
                        .HasForeignKey("YachtTourId");

                    b.Navigation("CityTour");

                    b.Navigation("Guest");

                    b.Navigation("Personnel");

                    b.Navigation("Transfer");

                    b.Navigation("YachtTour");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.TransferEntity", b =>
                {
                    b.HasOne("GuestFlow.Domain.Entities.Core.AirportEntity", "Airport")
                        .WithMany("Transfers")
                        .HasForeignKey("AirportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestFlow.Domain.Entities.Core.GuestEntity", "Guest")
                        .WithMany("Transfers")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestFlow.Domain.Entities.Core.PersonnelEntity", "Personnel")
                        .WithMany("Transfers")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestFlow.Domain.Entities.Core.VehicleEntity", "Vehicle")
                        .WithMany("Transfers")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airport");

                    b.Navigation("Guest");

                    b.Navigation("Personnel");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.YachtTourEntity", b =>
                {
                    b.HasOne("GuestFlow.Domain.Entities.Core.GuestEntity", "Guest")
                        .WithMany("YachtTours")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuestFlow.Domain.Entities.Core.PersonnelEntity", "Personnel")
                        .WithMany("YachtTours")
                        .HasForeignKey("PersonnelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Operations.GuestCityTour", b =>
                {
                    b.HasOne("GuestFlow.Domain.Entities.Core.CityTourEntity", "CityTour")
                        .WithMany("GuestCityTours")
                        .HasForeignKey("CityTourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuestFlow.Domain.Entities.Core.GuestEntity", "Guest")
                        .WithMany("GuestCityTours")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CityTour");

                    b.Navigation("Guest");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Operations.GuestYachtTour", b =>
                {
                    b.HasOne("GuestFlow.Domain.Entities.Core.GuestEntity", "Guest")
                        .WithMany("GuestYachtTours")
                        .HasForeignKey("GuestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GuestFlow.Domain.Entities.Core.YachtTourEntity", "YachtTour")
                        .WithMany("GuestYachtTours")
                        .HasForeignKey("YachtTourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guest");

                    b.Navigation("YachtTour");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.AirportEntity", b =>
                {
                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.CityEntity", b =>
                {
                    b.Navigation("Airports");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.CityTourEntity", b =>
                {
                    b.Navigation("GuestCityTours");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.GuestEntity", b =>
                {
                    b.Navigation("GuestCityTours");

                    b.Navigation("GuestYachtTours");

                    b.Navigation("Invoices");

                    b.Navigation("Transfers");

                    b.Navigation("YachtTours");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.PersonnelEntity", b =>
                {
                    b.Navigation("CityTours");

                    b.Navigation("DailyNotes");

                    b.Navigation("Invoices");

                    b.Navigation("Transfers");

                    b.Navigation("YachtTours");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.TransferEntity", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.VehicleEntity", b =>
                {
                    b.Navigation("Transfers");
                });

            modelBuilder.Entity("GuestFlow.Domain.Entities.Core.YachtTourEntity", b =>
                {
                    b.Navigation("GuestYachtTours");
                });
#pragma warning restore 612, 618
        }
    }
}
