// ISO 3166-1 alpha-2 country codes with Turkish names
export const COUNTRIES = [
  { code: 'TR', name: 'Türkiye' },
  { code: 'US', name: 'Amerika Birleşik Devletleri' },
  { code: 'GB', name: 'Birleşik Krallık' },
  { code: 'DE', name: 'Almanya' },
  { code: 'FR', name: 'Fransa' },
  { code: 'IT', name: 'İtalya' },
  { code: 'ES', name: 'İspanya' },
  { code: 'NL', name: 'Hollanda' },
  { code: 'BE', name: 'Belçika' },
  { code: 'CH', name: 'İsviçre' },
  { code: 'AT', name: 'Avusturya' },
  { code: 'SE', name: 'İsveç' },
  { code: 'NO', name: 'Norveç' },
  { code: 'DK', name: 'Danimarka' },
  { code: 'FI', name: 'Finlandiya' },
  { code: 'PL', name: 'Polonya' },
  { code: 'CZ', name: 'Çek Cumhuriyeti' },
  { code: 'GR', name: 'Yunanistan' },
  { code: 'PT', name: 'Portekiz' },
  { code: 'IE', name: 'İrlanda' },
  { code: 'RU', name: 'Rusya' },
  { code: 'UA', name: 'Ukrayna' },
  { code: 'RO', name: 'Romanya' },
  { code: 'BG', name: 'Bulgaristan' },
  { code: 'HU', name: 'Macaristan' },
  { code: 'SK', name: 'Slovakya' },
  { code: 'SI', name: 'Slovenya' },
  { code: 'HR', name: 'Hırvatistan' },
  { code: 'RS', name: 'Sırbistan' },
  { code: 'BA', name: 'Bosna Hersek' },
  { code: 'ME', name: 'Karadağ' },
  { code: 'MK', name: 'Kuzey Makedonya' },
  { code: 'AL', name: 'Arnavutluk' },
  { code: 'JP', name: 'Japonya' },
  { code: 'CN', name: 'Çin' },
  { code: 'KR', name: 'Güney Kore' },
  { code: 'IN', name: 'Hindistan' },
  { code: 'AU', name: 'Avustralya' },
  { code: 'NZ', name: 'Yeni Zelanda' },
  { code: 'CA', name: 'Kanada' },
  { code: 'MX', name: 'Meksika' },
  { code: 'BR', name: 'Brezilya' },
  { code: 'AR', name: 'Arjantin' },
  { code: 'CL', name: 'Şili' },
  { code: 'CO', name: 'Kolombiya' },
  { code: 'PE', name: 'Peru' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'EG', name: 'Mısır' },
  { code: 'ZA', name: 'Güney Afrika' },
  { code: 'MA', name: 'Fas' },
  { code: 'TN', name: 'Tunus' },
  { code: 'DZ', name: 'Cezayir' },
  { code: 'SA', name: 'Suudi Arabistan' },
  { code: 'AE', name: 'Birleşik Arap Emirlikleri' },
  { code: 'QA', name: 'Katar' },
  { code: 'KW', name: 'Kuveyt' },
  { code: 'BH', name: 'Bahreyn' },
  { code: 'OM', name: 'Umman' },
  { code: 'JO', name: 'Ürdün' },
  { code: 'LB', name: 'Lübnan' },
  { code: 'IL', name: 'İsrail' },
  { code: 'IQ', name: 'Irak' },
  { code: 'IR', name: 'İran' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'BD', name: 'Bangladeş' },
  { code: 'TH', name: 'Tayland' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'MY', name: 'Malezya' },
  { code: 'SG', name: 'Singapur' },
  { code: 'ID', name: 'Endonezya' },
  { code: 'PH', name: 'Filipinler' },
  { code: 'IS', name: 'İzlanda' },
  { code: 'LU', name: 'Lüksemburg' },
  { code: 'MT', name: 'Malta' },
  { code: 'CY', name: 'Kıbrıs' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'MC', name: 'Monako' },
  { code: 'AD', name: 'Andorra' },
  { code: 'SM', name: 'San Marino' },
  { code: 'VA', name: 'Vatikan' },
].sort((a, b) => a.name.localeCompare(b.name, 'tr'))

export const getCountryName = (code: string): string => {
  const country = COUNTRIES.find((c) => c.code === code)
  return country ? country.name : code
}

export const getCountryCode = (name: string): string => {
  const country = COUNTRIES.find((c) => c.name === name)
  return country ? country.code : name
}

